-- Q1a
ALTER TABLE EMPLOYEE ADD COLUMN Office VARCHAR(4) DEFAULT 'X-0';

-- Q1b
UPDATE EMPLOYEE
SET Office = CASE 
	WHEN dno=1 THEN 'C-0'
	WHEN dno=4 THEN 'B-0'
	WHEN dno=5 THEN 'A-0'
	ELSE 'X-0'
END;

-- Q2a-b

ALTER TABLE DEPARTMENT ALTER COLUMN Mgr_ssn DROP NOT NULL;

ALTER TABLE EMPLOYEE DROP CONSTRAINT companyFK1;
ALTER TABLE EMPLOYEE  ADD CONSTRAINT companyFK1 FOREIGN KEY(Super_ssn)REFERENCES EMPLOYEE (Ssn) 
ON DELETE SET NULL
ON UPDATE CASCADE;
			
ALTER TABLE DEPARTMENT DROP CONSTRAINT companyFK7;
ALTER TABLE DEPARTMENT ALTER COLUMN Mgr_ssn DROP NOT NULL;
ALTER TABLE DEPARTMENT  ADD CONSTRAINT companyFK7 FOREIGN KEY(Mgr_ssn)
REFERENCES EMPLOYEE (Ssn)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE WORKS_ON DROP CONSTRAINT companyFK3;
ALTER TABLE WORKS_ON ADD constraint companyFK3 FOREIGN KEY(Essn)
REFERENCES EMPLOYEE (Ssn)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE DEPENDENT DROP CONSTRAINT companyFK6;
ALTER TABLE DEPENDENT  ADD constraint companyFK6 FOREIGN KEY(Essn)
REFERENCES EMPLOYEE (Ssn)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- Q3a
DELETE FROM EMPLOYEE 
WHERE fname='James' AND lname='Borg';

-- Q3b
UPDATE EMPLOYEE 
SET ssn='999999999' 
WHERE fname='Franklin' AND lname='Wong';

-- Q3c
INSERT INTO EMPLOYEE 
VALUES('Hermione','J','Granger','111111111','1979-09-19','123 Main st.','F',25000,'123456789',5,'A-0');

INSERT INTO EMPLOYEE
VALUES('Harry','J','Potter','777777777','1980-07-31','4 Privet drive.','M',20000,'111111111','5','A-0');

INSERT INTO EMPLOYEE
VALUES('Ron','A','Weasley','101010101','1980-03-01','Ottery st Catchpole, Devon.','M',20000,'999887777','4','B-0');


